#+TITLE:       cygwin
#+AUTHOR:      Will Chang
#+EMAIL:       changwei.cn@gmail.com
#+DATE:        2013-12-19 周四
#+URI:         /wiki/cygwin
#+KEYWORDS:    cygwin,linux
#+TAGS:        :cygwin:linux:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: cygwin的使用技巧
--------------------------------------------------------------------------

* 设置时区

 .bashrc

export TZ=Asia/Chongqing

* How do I get crontab started running when using cygwin?

I can't remember where I found it, but using this series of commands from the cygwin prompt got the crontab system enabled for me. First this command:

for cygwin 1.5:

<src>
cygrunsrv -I cron -p /usr/sbin/cron -a -D
</src>

for cygwin 1.7:

<src>

cygrunsrv --install cron --path=/usr/sbin/cron --desc='Cygwin cron service' --type=auto --neverexits -a '-n'

</src>
followed by:

net start cron

I haven't used this cygwin feature before, so it feels weird knowing that crontab is running on my Windows system under cygwin.

I don't have much in the crontab yet, just one entry that runs a wget command to a certain URL every night. Here's the actual crontab entry, which actually calls a Bourne shell script that I wrote for this purpose:

45 18 * * * /cygdrive/c/Al/Reports/do_nightly_wget.sh 

[[http://www.ibm.com/developerworks/cn/aix/library/au-spunix_cygwin/?ca=drs-tp4608][在 Windows 上使用 Cygwin]]


* Install

To tuning my desktop, I moved the cygwin from C:\dsw to E:\cygwin. first, I uninstalled the cygwin in C:\dsw with the cygwin
setup.exe. 

http://www.cygwin.cn/site/install/ 

http://www.cygwin.net.cn/

Add site: http://www.cygwin.cn 

Or input in URL http://www.cygwin.cn/pub/ 

Or input URL http://ftp.ntu.edu.tw/ftp/pub/cygwin/


Choose:

 - emacs, emacs-el, emacs-X11
 - wget
 - mercurial, cvs, subversion, git
 - aspell, aspell-en
 - xorg-server,xinit
 - openssh
 - unzip

Add cygwin\bin to %PATH%

** SSH 

http://pigtail.net/LRP/printsrv/cygwin-sshd.html

 1. create ssh server: ssh-host-config  -y 
 2. start sever: cygrunsrv  --start  sshd
 3. stop server: cygrunsrv  --stop  sshd


* Uninstall 

在这里我说一下这个问题的解决方案：记得在安装cygwin的时候那个setup文件了吗，我们卸载它也要用这个文件，进入setup后还在按照步骤下一
步....下一步，之后会来到您需要安装文件包的那个环节，如果你先前选择了All-install,则这些则把这一项改为all-uninstall即可。如果你之前
安装选择了自定义的安装，则把对应项改为uninstall即可。就是这么简单是吧！！！然后点击下一步，一切就都OK了！ 

* Install Emacs in cygwin

http://www.webalice.it/angelo.graziosi/cygwin/emacs/Emacs.html

* Display Chinese words

<example>

   1. .bashrc
      # 中文环境
      export LANG=en_US.UTF-8
      export LC_CTYPE="zh_CN"
      # 中文显示
      alias ls='ls --show-control-chars'
      alias dir='ls --show-control-chars'
      alias less='less --raw-control-chars'

   2. .inputrc
      # bash中中文输入/输出
      set convert-meta off
      set input-meta on
      set output-meta on

</example>

* Shell

<src> 

ln -s /cygdrive/c/standino ./standino 

ln -s "/cygdrive/c/My Documents/" ~/My_Documents

ln -s "/cygdrive/c/Documents and Settings/Administrator/Desktop" ~/Desktop

ln -s "/cygdrive/c/" /c

</src>

Terminal program: setting the terminal type to TTY
If you are using Emacs in the clumsy Windows "Command" window (command.exe), you might benefit from setting the terminal type so
that more control characters work. Do this by changing the startup script, cygwin.bat, to contain the following commands, setting
the CYGWIN tty and binary modes. For example: 
<src>
@echo off

C:
chdir \cygwin\bin

set CYGWIN=tty binmode
bash --login -i 
</src>
    - install rxvt from setup.exe
    - copy the cygwin.bat startup script in your Cygwin root directory, e.g. C:\cygwin\cygwin.bat to C:\cygwin\cygwin-rxvt.bat
    - Make the following change to cygwin-rxvt.bat

<src>
@echo off

C:
chdir C:\cygwin\bin

set SHELL=/bin/bash
rxvt --loginShell -sr
#bash --login -i
</src>

get from server : <src> rsync -avuz -e ssh --delete changwei.dyn.webahead.ibm.com:/Latest / </src>


* SSH without password

 1. 分别从A和B上登录作为root后运行ssh-keygen，目的是简单地在/root下创建目录.ssh,当提示输入
　　 passphase时打入两次回车。这将生成/root/.ssh/identity and/root/.ssh/identity.pub
 2. 先测试一下，从A登录作为root，打入#ssh B,会要求提示root password。
 3. 现在从A登录作为root，运行 <src>scp ~/.ssh/id_rsa.pub changwei.dyn.webahead.ibm.com:~/.ssh/authorized_keys</src>　　文件名必须不能弄错。
 4. 现在再从A运行#ssh B则不需要密码了：)


* DB2 

I have different machines with cygwin and db2 installed 
There is 1 machine that is acting differently from the other machines, although I don't modify many setting in cygwin/windows 
The case is that if I connect to database : this is successfull but this connection is immediatly lost. I execute another command against the db and message indicates : no connection.   as if the connect would be executed in a different shell (subshell) and not this connection not available in the current shell. 
Anyone already encountered this or any idea which setting could force this ? 
I start db2cmd /i /c /w c:\cygwin\cygwin.bat to get the db2 window with cygwin interface on all machines. 
Thanks for all info 
Best Regards, Guy Przytula

------------------------------------------------------------------------------------------------------

Just to inform others that the problem has been corrected by db2 team. 
export DB2CLP=**$$**   corrected the problem... 
Best Regards, Guy Przytula


cygpath工具提供了在shell脚本中进行win32-posix路径格式转换的能力。


* 如何打造绿色版cygwin

You can use 
<src>
 mount -m > mymount.bat
</src>
to generate a mount bat

Yesterday I wanted to reinstall cygwin on my notebook. I just copied the whole cygwin directory from desktop to notebook. When I run cygwin.bat, it always complained that "bash.exe: could not find /tmp, please create!".

There is something wrong with cygwin's mount table. According to cygwin faq, To save the mount information to a file for later restoration, use `mount -m > mounts.bat' To remove all mount information use `umount -A'. To reincorporate saved mount information just run the batch file.
Displaying the current set of mount points

<src>
c:\> mount
f:\cygwin\bin on /usr/bin type system (binmode)
f:\cygwin\lib on /usr/lib type system (binmode)
f:\cygwin on / type system (binmode)
e:\src on /usr/src type system (binmode)
c: on /cygdrive/c type user (binmode,noumount)
e: on /cygdrive/e type user (binmode,noumount)
</src>

Run mounts.bat to setup mount points to solve the problem

No bash command, just run mount from cmd.exe. At that moment, bash still complains "no /tmp", we can't use it, use mount directly. After we run this batch file, we can check system-wide registry "HKLM/Software/Cygnus Solutions/Cygwin/mounts2".
<src>
mount -f -s -b "d:/cygwin/bin" "/usr/bin"
mount -f -s -b "d:/cygwin/lib" "/usr/lib"
mount -f -s -b "d:/cygwin" "/"
mount -s -b --change-cygdrive-prefix "/cygdrive"
</src>
Following are from cygwin's faq

The mapping is stored in the current user's Cygwin mount table in the Windows registry so that the information will be retrieved next time the user logs in. Because it is sometimes desirable to have system-wide as well as user-specific mounts, there is also a system-wide mount table that all Cygwin users inherit. The system-wide table may only be modified by a user with the appropriate privileges (Administrator privileges in Windows NT).

The current user's table is located under "HKEY_CURRENT_USER/Software/Cygnus Solutions/Cygwin/mounts v" where is the latest registry version associated with the Cygwin library (this version is not the same as the release number). The system-wide table is located under the same subkeys under HKEY_LOCAL_MACHINE. The user mount table takes precedence over the system-wide table if a path is mounted in both. This includes the setting of the cygdrive prefix.

The mount command can set the POSIX root / to any directory in the Windows file system. In absence of such a mount, Cygwin maps / to the root of the current Windows working directory (for example, H:\ or \\computer\share). Normally Cygwin's setup.exe creates the initial mount point for the POSIX root. 



* cyg-apt

http://software.jessies.org/salma-hayek/cygwin-setup.html

http://download.linuxaudio.org/lilypond/binaries/cygwin/cyg-apt



* Reference 

   1. [[http://forum.ubuntu.org.cn/viewtopic.php?f=8&t=66302][ 终端软件的选择：rxvt-unicode]]
   1. http://www.khngai.com/emacs/cygwin.php
   1. [[http://www.yuanma.org/data/2007/0403/article_2487.htm][Cygwin上ssh服务的putty自动登录问题]]
   1. [[http://blog.csdn.net/easwy/archive/2007/10/05/1812242.aspx][使用rxvt做为cygwin终端]]
   1. [[file://C:/dsw/usr/share/doc/cygwin-doc-1.4/cygwin-api.html][Cygwin API Reference]]
   1. [[file://C:/dsw//usr/share/doc/cygwin-doc-1.4/html/faq/index.html][Cygwin FAQ]]
   1. [[file://C:/dsw//usr/share/doc/cygwin-doc-1.4/html/cygwin-ug-net/index.html][Cygwin User's Guide]]
   1. [[file://C:/dsw//usr/share/doc/cygwin-doc-1.4/cygwin-ug-net.html][User's Guide (One file)]]
 
