#+TITLE:       《尽管去做－－－无压工作》读书笔记
#+AUTHOR:      Will Chang
#+EMAIL:       changwei.cn@gmail.com
#+DATE:        2013-12-19 Thu
#+URI:         /wiki/html/gtd
#+KEYWORDS:    gtd
#+TAGS:        :gtd:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 《尽管去做－－－无压工作》读书笔记



http://davidlaing.com/2009/05/31/the-pomodoro-technique-scrum-in-the-small/


   焦虑是由于缺乏控制力,组织管理、准备和行动不足所造成
    的。
   ——戴 维 ·凯 克 奇 ( David·Kekich)

   想要获取高效益,一定要明确地认定预期结果。
    自下而上的方法反而更加行之
有效。

 1.(1)收集一切引起我们注意力的事情; 
 2.(2)加工处理后,确定它们的实质以及解决方法;
 3.(3)组织整理得出的结论;
 4.(4)把它们列为我们行动的选择方案;
 5.(5)行动,


定期清空收集工具


  面对每一件需要处理的信息时,你必须作出两个方面的决定:
1. 你已经承诺完成哪些工作?需要达到什么样的结果?
2. 下一步需要采取的行动是什么?


  一旦你的下一步行动方案出台,紧接着,你面临三种选择:
  处理这件事。如果你能够在不到 2 分钟的时间内就搞定它,那么,一旦这项工作
被确定,你就应该立刻着手落实。
  把这件事指派给别人去处理。如果处理这件事情需要花费的时间不止 2 分钟,那
么,你应该问一问自己,你是否就是解决这个问题的最佳人选呢?如果回答是否定的,
那就干脆委托给一个合适的人员去办理。
   延迟处理。如果处理的时间超过了 2 分钟,而你又恰恰是最佳人选,这时,你不
得不推迟行动,把它记录在某一个或者多个“下一个行动”的清单上。

  这些工作不需要按照某一种特殊的顺序进行排列。你只需把它们列在一张主清单
上,以便经常地查阅它们就足够了。

      每周你再次浏览一下那些未完善的工作和悬而未决的问题,我把这称之
为万英尺高度。你应该把握住这个机会,快速地清理一下自己面临的行动和抉择,从
而从根本上对某一时间需要处理的工作作出有效的选择。


根据你的需要,经常地回顾你的清单,把它们赶出你的大脑。


每周查阅也就是做下列事情:
  收集和加工处理所有的“材料”。
  回顾和检查你的系统。
  更新各类清单。
  做到清洁、清楚、实时和完整。

          你如何选择下一步行动呢?你可以按照次序采用下面 4
个标准:
 1. 环境
 2. 有多少时间
 3. 有多少精力
 4. 重要性


 .评估每日工作的 3 种模式
   当你着手处理事务,也就是人们在一般情况下提到的“工作”时,你可能是在从
事以下 3 种不同类型的活动:
    1. 处理事先安排好的工作
    2. 处理随时冒出来的事件
    3. 规划 定义你自己的工作

5 万英尺以上:生活
4 万英尺:3~5 年的展望
3 万英尺:1~2 年的目标
2 万英尺:责任范围
1 万英尺:当前的工作
跑道:目前的行动

  轻松自如地控制一切的主要因素是:(1)明确判定工作的预期结果以及下一步具
体行动;
   (2)把一切尚待解决的工作的提示信息安置在一个安全可靠的系统中,并定
期回顾和检查。这就是我所命名的横向工作重心。

 大脑只有经过 5 个步骤才能够完成任何一项任务:
1. 定义目标和原则
2. 展望成果
3. 集思广益
4. 组织管理
5. 明确下一步的行动方案


目的
  问一问“为什么”这个问题你永远都不会受到任何损失的。如果你目前从事的所
有事情在初始阶段都经过了细致周密的安排,那么它们都有机会进一步改进,甚至获
                                    67
                 第 3 章 纵向管理:巧妙制定工作计划
得某种激励。你为什么打算参加下一次会议呢?你工作的中心意图是什么呢?你为什
么 请朋 友们在 你家 的后院 里烧 烤聚餐 呢? 你为什 么雇佣 了一 位市场 营销 经理呢 ?你
为什么设立自己的预算呢?


原则


前景/结果

                                             成功将是
一 番什 么样的 景象 ?听上 去会 怎样? 有什 么的感 觉呢? 目标 和原则 提供 了动机 和监
控手段,而前景则是描绘最终成果的一个现实的蓝图。这就是一个“什么”的问题,
而不是“为什么”的问题。当这项工作或者形势成功地呈现在这个真实的世界上时,
到底会是怎样一番景象?


聚焦的力量


阐明结果
   你那富有感知力的过滤装置是如何运转的呢?认识到这一点,你将从中发现一个
简朴却意义深远的原理:直到亲眼看到自己做这件事,你才能够对其运作方法有所了
解。

集思广益

开动脑筋的关键技巧
  有许多技巧都可以用来启动思维,强化打破常规的思考模式。这些基本原则可以
归纳为以下 3 点:
    不判断,不质疑,不评估,不批判。
    追求数量,不求质量。
    把分析组织工作置于次要的位置上。


* Brian Tr a c y ’s THE ULT I M ATE GOALS PROGRAM

** Session 1: Unlocking Your True Potential

1. Imagine that you have the inborn ability to achieve any goal you could ever set for
   yourself. What do you really want to be, have, and do?

 - Be a billionaire 
 - Good health. Play tennis well
 - Good at sing
 - 会察言观色，会说话。让每个人都喜欢我。

2. What are the activities that give you your greatest sense of meaning and purpose
   in life?

 - Build a good software
 - Enjoy the free time

3. Look at your personal and work life today and identify how your own thinking has
   created your world. What should you, could you, change?

 - Stop worrying 
 - Focus on learning new skills
 - Be happy

4. What do you think and talk about most of the time: what you want or what you
   don’t want?

 - Have enough money 
 - Be good at my current job
 - Be good at do the right things

5. What is the price you will have to pay to achieve the goals that are most important
   to you?

 - Read books
 - Work hard
 - Ask some experts for help

6. What one action should you take immediately as the result of your answers to the
   above questions?

 - Read books
 - Work hard
 - Ask some experts for help

** Session 2: Taking Charge of Your Life

1. Identify your biggest problem or source of negativity in life today. In what ways are
   you responsible for this situation?

 - I am afraid I can not do something well
 - My English is poor

2. See yourself as the President of your own company. How would you act differently if
   you owned 100% of the shares?

 - Spend time on improving my English skill
 - Thinking from the view of other people

3. Resolve today to stop blaming anyone else for anything and instead accept complete
   responsibility in every area of your life. What actions should you be taking?

 - Try to find out the way to resolve the problem

4. Stop making excuses and start making progress. List some of your favorite excuses.
   Now, imagine that they have no basis in fact and act accordingly.

5. See yourself as the primary creative force in your own life. You are where you are and
   what you are because of your own choices and decisions. What should you change?



6. Make a list of anyone you need to forgive in your life. Now, resolve today to forgive
   anyone who has ever hurt you in any way. Let it go. Refuse to discuss it again.
   Instead, get so busy working on something that is important to you that you don’t
   have time to think about it again.

