#+TITLE:       js.org
#+AUTHOR:      Will Chang
#+EMAIL:       changwei.cn@gmail.com
#+DATE:        2013-12-19 Thu
#+URI:         /wiki/html/js
#+KEYWORDS:    js
#+TAGS:        :js:jquery:dojo:ajax:定位元素:调试:piwik:网站统计:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION:  Javascript


 - [[http://www.myexception.cn/javascript/407684.html][DOJO js 根本dom操作]]
 - http://folyred.iteye.com/blog/946565
 - https://dojotoolkit.org/reference-guide/1.7/dojo/dom-construct.html
 - [[http://jinlong.github.io/blog/2013/08/29/devtoolsecrets/][浏览器开发工具的秘密]]
 - [[http://www.cnblogs.com/wukenaihe/archive/2013/01/27/javascript%E8%B0%83%E8%AF%95.html][Chrome developer tool介绍（javascript调试）]]
 - [[http://www.jb51.net/article/18111.htm][jquery控制div下所有连接]]
 - [[https://micate.me/debug-jquery-object-binded-events.note][获取绑定在 jQuery 对象上的事件]]
 - [[http://www.divcss5.com/jiqiao/j497.shtml][jQuery适用技巧笔记整合]]

*  [[http://www.w3cschool.cc/bootstrap/bootstrap-intro.html][Bootstrap 简介]]

  - [[https://wrapbootstrap.com/][Theme and temaplate]]
  - http://reactiveraven.github.io/jqBootstrapValidation/
Bootstrap 是一个用于快速开发 Web 应用程序和网站的前端框架。

在现代 Web 开发中，有几个几乎所有的 Web 项目中都需要的组件。

Bootstrap 为您提供了所有这些基本的模块 - Grid、Typography、Tables、Forms、Buttons 和 Responsiveness。

此外，还有大量其他有用的前端组件，比如 Dropdowns、Navigation、Modals、Typehead、Pagination、Carousal、Breadcrumb、Tab、Thumbnails、Headers 等等。

有了这些，你可以搭建一个 Web 项目，并让它运行地更快速更轻松。

* UI调试工具Fiddler,微软开发的。
* 获得jquery绑定的事件an


#+BEGIN_SRC javascript

var events = $(".add").data('events');
if (events && events.click) {



    // jQuery 1.4.x+
    $.each(events.click, function(key, handlerObject) {
        console.info(handlerObject.handler);
    });
}

#+END_SRC


* $.ajax 在IE中不work

#+BEGIN_SRC javascript
        $.ajaxSetup ({
            cache: false //关闭AJAX相应的缓存
        });

#+END_SRC

* firebug
 - [[http://mynoteweb.com/node/114][用Firebug调试JavaScript]]

* Jquery 查询对象的几种方式

  | 查询方式                 | 例子                                          |
  | 按class查询              | $(".myclass")                                 |
  | 按ID查询                 | $("#myid")                                    |
  | 定位某个元素，查找子元素 | $(".quickMenu i").bind('click', function () { |
  | 函数里获得this的子元素   | $(this).find('i').toggleClass("ticked");      |
  |                          |                                               |


* Jquery widget 编写
#+BEGIN_SRC javascript


var Green5  = {
        getLevel: function () { return this.options.level; },
        setLevel: function (x) {
                var greenlevels = this.options.greenlevels;
                var level = Math.floor(Math.min(greenlevels.length-1, Math.max(0,x)));
                this.options.level = level;
                this.element.css({background: greenlevels[level]});
                this._trigger('change', 0, level);
        },
        _init: function() { this.setLevel(this.getLevel()); }, // grab the default value and use it
        darker: function() { this.setLevel(this.getLevel()-1); },
        lighter: function() { this.setLevel(this.getLevel()+1); },
        off: function() {
                this.element.css({background: 'none'});
                this._trigger('done');
                this.destroy(); // use the predefined function
        },
        options: {
                level: 15,
                greenlevels: ['#000','#010','#020','#030','#040','#050','#060','#070','#080','#090','#0a0','#0b0','#0c0','#0d0','#0e0','#0f0', '#fff']
        }
};
$.widget("ui.green5", Green5);
#+END_SRC

#+BEGIN_SRC html
        <p class="target">This is a test paragraph with green level <span class="level">undefined</span>.</p>
#+END_SRC
#+BEGIN_SRC javascript

//  The on button above does the following:
$('.target').green5({
        change: function(event, level) { $('.level', this).text(level); } // callback to handle change event
});
$('.target').bind('green5done', function() { $('.level', this).text('undefined');alert('bye!') }); // event handler for done event

#+END_SRC

** Involving the Mouse
Now, a lot of what we want to do with widgets involves mouse tracking, so ui.core.js provides a mixin object that includes lots of
useful methods for the mouse. All we need to do is add the $.ui.mouse widget to our widget prototype:

#+BEGIN_SRC javascript


var Green6 = {mouse-overriding function and widget-specific functions};
$.widget ('ui.green6', $.ui.mouse, Green6);
#+END_SRC
And override $.ui.mouse's functions (_mouseStart, _mouseDrag, _mouseStop) to do something useful, and call this._mouseInit in your
this._init and this._mouseDestroy in your this.destroy. The mouse defaults are automagically including in your options object; see
the mouse code for details.

Let's add some mouse control to our greenerizer:
#+BEGIN_SRC javascript



Green6 = $.extend({}, $.ui.green5.prototype, { // leave the old Green5 alone; create a new object
        _init: function(){
                $.ui.green5.prototype._init.call(this); // call the original function
                this._mouseInit(); // start up the mouse handling
        },
        destroy: function(){
                this._mouseDestroy();
                $.ui.green5.prototype.destroy.call(this); // call the original function
        },
        // need to override the mouse functions
        _mouseStart: function(e){
                // keep track of where the mouse started
                this.xStart = e.pageX; // not in the options object; this is not something that can be initialized by the user
                this.levelStart = this.options.level;
        },
        _mouseDrag: function(e){
                this.setLevel (this.levelStart +(e.pageX-this.xStart)/this.options.distance);
        },
        options: {
                level: 15,
                greenlevels: ['#000','#010','#020','#030','#040','#050','#060','#070','#080','#090','#0a0','#0b0','#0c0','#0d0','#0e0','#0f0', '#fff'],
                distance: 10
        }
});
$.widget("ui.green6", $.ui.mouse, Green6);
#+END_SRC

#+BEGIN_SRC html


        <p class="target">This is a test paragraph with green level <span class="level">undefined</span>.</p>
#+END_SRC

The ever-alert reader will note what we've just done: subclassed green5 to make green6, including calls to "super" methods. This
ought to be abstracted out into its own method, something like

#+BEGIN_SRC javascript


$.ui.green5.subclass("green6", $.ui.mouse, {mouseStart:function(){}, mouseDrag: function(){}})
#+END_SRC

* piwik

 API: http://developer.piwik.org/api-reference/tracking-javascript#where-can-i-find-the-piwik-tracking-code

* [[http://www.bootcss.com/][Bootstrap]]

* SSI

  http://blog.csdn.net/cpp_lzth/article/details/6167591

* Node.js
  1. 在Windows下安装Node.js、npm、express http://blog.uifanr.com/2013/03/12/472
** [[http://getkickstrap.com/docs.html#/first-steps][kickstrap]]


  https://www.firebase.com/tutorial/#session/va7gdy2y5s0

* ajax 乱码
encodeURIComponent(

#+BEGIN_SRC


  $.ajax({
    url: "/contact/list?keyword="+encodeURIComponent(keyword)+"&pageNum="+page,
    dataType : "json",
    success : function(data) {
#+END_SRC
