#+TITLE:       mysql
#+AUTHOR:      Will Chang
#+EMAIL:       changwei.cn@gmail.com
#+DATE:        2013-12-19 Thu
#+URI:         /wiki/html/mysql
#+KEYWORDS:    mysql,sql
#+TAGS:        :mysql:mybatis:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION:  MySQL数据库


 - [[http://blog.csdn.net/adparking/article/details/6676571][mysql中的load data infile用法]]
 - [[http://www.blogjava.net/qileilove/archive/2012/04/23/376353.html][定时备份mysql数据库 并删除7天前的备份 （windows linux ）]]
 - [[http://blog.csdn.net/jinkelei/article/details/6833997][mysql定时备份和删除]]
 - [[http://my.oschina.net/zimingforever/blog/91287][mysql删除大表的部分数据]]


* mybatis like

        AND (find_in_set(#{tags},tags)
                                OR name LIKE CONCAT(CONCAT('%', #{tags}),'%')
                                OR contactor LIKE CONCAT(CONCAT('%', #{tags}),'%')

* Communications link failure
 
 - http://zeusami.iteye.com/blog/1112827

2.直接用sql命令行修改  mysql> set global wait_timeout=604800; 
2.直接用sql命令行修改  mysql> set global wait_timeout=604800; 

除了wait_timeout，还有一个'interactive_timeout' 

同样可以执行SHOW GLOBAL VARIABLES LIKE  'interactive_timeout'来查询 
执行set global interactive_timeout=604800;来设置

* trim
  1. http://blog.itpub.net/25281640/viewspace-710084/

SQL 中的 TRIM 函数是用来移除掉一个字串中的字头或字尾.最常见的用途是移除字首或字尾的空白.
TRIM ([[位置] [要移除的字串] FROM ] 字串): [位置] 的可能值为 LEADING (起头),TRAILING (结尾), or BOTH (起头及结尾).这个函数将把 [要移除的字串] 从字串的起头、结尾，或是起头及结尾移除.如果我们没有列出 [要移除的字串] 是什么的话，那空白就会被移除.
TRIM(字串): 将所有字串起头或结尾的空白移除
LTRIM(字串): 将所有字串起头的空白移除.
RTRIM(字串): 将所有字串结尾的空白移除.

* case 

 1. http://www.phpzixue.cn/detail1064.shtml



CASE 
WHEN price IS NULL THEN 'Unpriced' 
WHEN price < 10 THEN 'Bargain' 
WHEN price BETWEEN 10 and 20 THEN 'Average' 
ELSE 'Gift to impress relatives' 
END 


* mysql coalesce的函数用法


 http://huangyunbin.iteye.com/blog/1137815


实例一： 

              select coalesce（null,"carrot","apple"） 

          返回结果：carrot 

       实例二： 

              select coalesce(1,"carrot","apple") 

           返回结果：1 

        友情提示：coalesce里的参数如果是字符串的话，务必用单引号或者双引号廓起来； 

                           这些语句可以直接在mysql里运行。

* 导出数据库表结构

#+BEGIN_SRC
 mysqldump -u root -h 192.168.229.76 -P 3306  -p dashboard calculate_data_job

 mysqldump -u root -h 192.168.229.76 -P 3306  -p piwik  piwik_user_dashboard
 mysqldump -u root -h 192.168.229.76 -P 3306  -p piwik  piwik_segment

#+END_SRC
* 建立索引

CREATE INDEX index_name ON table_name (column_list)