#+TITLE:       pm
#+AUTHOR:      Will Chang
#+EMAIL:       changwei.cn@gmail.com
#+DATE:        2013-12-19 Thu
#+URI:         /wiki/html/pm
#+KEYWORDS:    pm
#+TAGS:        pm
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: PM

1. Project

- unique process
- with start and finish dates
- limit resource 

A project is a temporary endeavor undertaken to produce a unique product or service.
A project is a unique process, consisting of a set of coordinated and controlled activities with start and
finish dates, undertaken to achieve an objective that conforms to specific requirements, including the
constraints of time, cost, and resources (from ISO 10006).

2 Stakeholder

Any group or individual who is impacted by or who could impact the
project, 


3. Groups mature and develop in a clearly defined four-stage cycle
 
form storm norm perform 

4. performance get improved. 

5.Chart,  give the project exiting, product description , pm authority 

Project definition doc is different than Chart. it is PM create it for the team members. 

6 Requirement, specific word. 


7 Decoposition

  OBS, WBS, PBS

  PBS ---what, WBS --- how, OBS --- who

8 Functional, projec, maix 

In Fuctional, PM has less authority 

9 Risk 

 identify risk: brain storming, root cause identification, risk factor/check list. 

Isure is minigation method. 

Impact, potability, 

Risk rating matrix

Low impact Low possibly, accept. 

Every risk has contain stratege 

Contengecny, GCG PM can not use contegency. Japan has 25%

PM will not invite client to discuss risk, only if the risk is depend of customer.

10 Esitmiation

top down

button up 

WBS is button up. 

top down is easy and less cost. is not very accurate. 

Gutta 

Milestone chart for excitive 

 11. base line

after stake holder approve, the base line is created. 

effort: amount of labor unit

12. critical path, float is zero 


13 change control

approve, reject, defer. 

 PM, key stakeholder , canalize impact. 

CV >0 
sv <0 delay

add more resource to catch up schedule.

14. 

Trouble project, requirement issue. 

tech issue is not key issue.

15 seven keys is not methodology , it is a communicate tool. 

WWPAM is methodology 

16 close is day one. 

