#+TITLE:       敏捷软件开发
#+AUTHOR:      Will Chang
#+EMAIL:       changwei.cn@gmail.com
#+DATE:        2013-12-19 Thu
#+URI:         /wiki/html/scrum
#+KEYWORDS:    scrum,agile,软件开发
#+TAGS:        :scrum:agile:软件开发:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION:  敏捷软件开发

"不管白猫黑猫，抓到老鼠就是好猫"。软件开发也是，我们不要形而上学的敏捷，而且是要考虑为什么要敏捷。敏捷的目的是，能够快速开发软件满
足用户需求。这个是根本目的，所有不能达到这个目的的做法，都需要去改进，无论那种做法是不是披着敏捷的外衣。

* 管理3.0

管理3.0关注于敏捷领导与管理者的以下几个特征：

培养能力：管理者应帮助队员培养能力，从而实现他们的目标。给他们机会去做一些有挑战性的任务，帮他们提高工作能力。
发展结构：创建一个能增强队员间沟通与协作的结构。
改进一切：人、团队、机构都应专注于持续改善，从而延缓失败。
激励队员：管理者应该帮助队员们增加动力，鼓励他们更具创造力和活力。
授权团队：管理要支持队员们变得具有自发性，授予他们决定权。
协调约束：自组织要求系统周围存在一个外围边界。外围边界引导自组织团队创造价值。

* Scrum
 1. http://www.infoq.com/cn/articles/scrum-pseudo-code


* 全员会议

  - 开发管理 CheckLists(11) -敏捷开发 SCRUM全员会议 http://jlins.iteye.com/blog/1354544


** 议程
*** 欢迎和接收
与会人员介绍参与会议的所有名单头衔，和联络方式

*** 介绍会议的目的

  - 澄清项目有关概念，确定项目愿景
  - 确保大家对项目的管理方法、角色和责任、变更管理方法等认可

*** 介绍项目背景

敏捷实践已作为研发部重点流程改进在推荐，前期与松涛、刘健经理沟通，会尝试用采销罗盘作为零售平台敏捷试点。产品、开发、和测试请全力支持敏捷流程试点，并后续作为最佳实践进行零售平台推广。

*** 说明项目相关角色和责任

  - 产品负责人： 产品负责人是利益相关方的代表,他的工作重点是产品的业务方面。他负责向团队介绍产品远景。他负责给出一份明确的,可度量的,合理的产品 Backlog,并从业务角度出发对 Backlog 中各项问题按优先级排序。
  - 团队： 团队尽一切可能去完成任务——发布产品。团队需要全面的能力,这意味小组内拥有实现产品的全部技术和技能。团队还需要充分的理解产品负责人所描述的产品愿景以及 Sprint 目标,以更好地支持可能需要进一步开发的产品的发布。
  - Scrum Master： Scrum Master 是整个团队的导师和组织者,他负责提高团队的开发效率。他常提出培训团队的计划,列出障碍 Backlog。Scrum
    Master 控制着检查和改进 Scrum 的周期,他维护这一团队的正常运行,并与产品负责人一起让利益相关方获得最大化投资回报。他关心的是这些
    敏捷开发思想是否能得到利益相关方的理解和支持。
  - PM：负责与外部人员沟通，为团队屏蔽掉干扰，解决障碍。需要一个比较强势的人物。

*** 介绍将采用的管理方式
   - 项目周期
   - Sprint 时间表
   - 产品 Backlog的格式，使用什么工具记录跟踪(立项然后使用pmp管理？)
