#+TITLE:      Tools
#+AUTHOR:      Will Chang
#+EMAIL:       changwei.cn@gmail.com
#+DATE:        2013-12-19 Thu
#+URI:         /wiki/html/tool
#+KEYWORDS:    tool
#+TAGS:        :tool:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION:  Tools

* 开发环境安装手册

** VPN Proxy 

 - https://code.google.com/p/goagent/ 

** [[www.cygwin.com][Cygwin]]

安装下面的软件：

 - emacs-win32
 - wget
 - mercurial, cvs, subversion, git
 - aspell, aspell-en
 - openssh
 - unzip
  
*** [[https://github.com/cfg/apt-cyg][apt-cyg]]

 curl -o /usr/bin/apt-cyg https://raw.github.com/cfg/apt-cyg/master/apt-cyg

 chmod +x /usr/bin/apt-cyg


** 安装emacs 

打开cygwin 命令行，使用下面的命令获得emacs的配置。具体参考[[https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/guide-zh.org][一年成为Emacs高手(像神一样使用编辑器)]]

git clone https://github.com/standino/emacs.d.git ~/.emacs.d

用下面的命令启动emacs,使用本地代理

http_proxy=http://127.0.0.1:8087 emacs -nw

安装[[https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/guide-zh.org][一年成为Emacs高手(像神一样使用编辑器)]]中提到的插件和第三方工具

*** org-refresh-category-properties: Invalid function
使用 emacs -q启动，然后安装新版本的Org


* Selenium 

 http://code.google.com/p/selenium/

 [[http://www.ibm.com/developerworks/cn/web/wa-testweb/index.html?ca=drs-][使用 Selenium RC 测试 web 应用程序]]


* [[http://prism.mozilla.com/started/][Prism]]


* [[http://ichi2.net/anki/wiki/html/][Anki]]

学习英语的好工具。

** Swac plugin for Anki

http://polyglotte.tuxfamily.org/autres/anki_swac_en.html

** [[http://smart.fm/][Smart fm]]

 1. http://smart.fm/goals/124950
 2. http://smart.fm/goals/124973  
 3. http://smart.fm/goals/124991 
 4. http://smart.fm/goals/124999  
 5. http://smart.fm/goals/124990 --
 6. http://smart.fm/goals/125288
 7. http://smart.fm/goals/125303
 8. http://smart.fm/goals/125318
 9. http://smart.fm/goals/125585
 10. http://smart.fm/goals/125598
 11. http://smart.fm/goals/125611
 12. http://smart.fm/goals/126276
 13. http://smart.fm/goals/126541
 14. http://smart.fm/goals/126551
 15. http://smart.fm/goals/126594
 16. http://smart.fm/goals/126550
 17. http://smart.fm/goals/126662
 18. http://smart.fm/goals/126676
 19. http://smart.fm/goals/127003
 20. http://smart.fm/goals/127022
 21. http://smart.fm/goals/127040
 22. http://smart.fm/goals/127039

* PQMagic

http://w3.webahead.ibm.com/w3ki/display/linuxportal/Downloading+Partition+Magic+for+Windows 




* Shutdown or restart machine 

 - windows restart: shutdown -r -t 0
 - windows shutdown: shutdown -s -t 0
 - Linux restart: sudo reboot
 - Linux shutdown: sudo shutdown -P  now
 - 



** [[http://findbugs.sourceforge.net/][FindBugs]]

 1. [[http://findbugs.sourceforge.net/manual/installing.html][Installing FindBugs™]]
 2. [[http://findbugs.sourceforge.net/manual/anttask.html][Using the FindBugs™ Ant task]]
 3. [[http://findbugs.sourceforge.net/manual/datamining.html#antexample][Ant example]]

** [[http://pmd.sourceforge.net/][PMD]]

 1. [[http://pmd.sourceforge.net/ant-task.html][PMD Ant Tasks]]
 2. [[http://pmd.sourceforge.net/howtomakearuleset.html][How to make a new rule set]]


* wink

http://blog.sina.com.cn/s/blog_46dac66f0100008g.html

http://debugmode.com/wink/

http://xbeta.info/free-wink.htm

* [[../etc/vi.html][VI]]


vim(vi)是Linux中功能强大的编辑工具。vim有3中主要的模式：

 1.normal mode：当进入vim时，默认的模式就是normal mode。在此模式下，无法输入任何文字，不过可以利用按键命令来执行许多操作命令，例如移动光标位置、复制、删除。

 2.insert mode：进入vim输入a、i、或o键。即可进入insert mode，此模式下可以输入文字内容。

 3.command-line mode：在norma lmode中输入“:”即会进入command-line mode，在此模式下，可以做一些与输入文字无关的事，例如搜索字符串、保存文件或结束编辑等。

在normal mode下：

h：将光标向左移动一格

l：将光标向右移动一格

j：将光标向下移动一格

k：将光标向上移动一格

ctrl+b：将页面向前卷动一页

ctrl+f：将页面向后卷动一页

0：将光标移到该行最前面

$：将光标移到该行的最后面

G：将光标移到最后一行的开头

w或W：将光标移到下一个字

若输入“w”，则标点符号如“.”，“,”，“/”等字符都被当成一个字

e或E：将光标移到本单字的最后一个字符；如果光标所在位置为本单子的最后一个字符，则跳到下一个单字的最后一个字符。

若输入“w”，则标点符号如“.”，“,”，“/”等字符都被当成一个字

b：将光标移到本单词的第一个字符；如果光标所在位置为本单词的第一个字符，则跳到上一个单字的第一个字符。

ctrl+u：将光标向前移动半页

ctrl+d：将光标向右移动半页

ctrl+e：屏幕向下卷动一行，也可以说文章和光标向上卷动一行

ctrl+y：屏幕向上卷动一行，也可以说文章和光标向下卷动一行

在command-line mode下：

e 文件的路径及名称：打开指定文件

a：从当前光标所在的位置的下一个字符开始输入

i：在光标所在的位置插入新输入的字符

o：新增加的一行，并将光标移到下一行的开头

w：文件的路径及名称 保存文件

q：退出vim

Vim的常用操作命令

复制文字

yy：可将光标目前所在位置的正行复制，复制时不会将文字反白显示

nyy：其中n为数字键，表示要复制的行数，若按3yy，则连同光标所在的位置的一行，与下面2行一起复制

yw：可复制光标所在位置到整个单词结束的字符

nyw：n表示要复制的单词数目，若按3yw，则会将目前光标所在位置到单词结束，以及后面的2个字一起复制

p：可将复制的文字粘贴到当前光标所在的位置。若复制的是整行文字，则会将整行内容粘贴在光标所在位置的下一行

删除文字

d：先按d键，放开后按←键，可将光标位置前一个字符删除；按→键，则会将光标位置的字符删除；按↑键，可将当前光标所在的行与前一行一并删除。按↓键，可将当前的光标所在的行与下一行删除。

D：可删除一行中光标所在位置之后的所有字符。

dd：连续按2次d键可删除光标所在的那一行。

dw：将光标停在某个字的第一个字符，按dw键时，会将此字整个删除。如将光标置在某个字中间的字符上，则会将此字中光标后面的字符删除。

nd：n为数字，如按3d，再按下↑键，则删除光标上方的3行，再包括本身1行，共删除4行。若按下↓键，则删除光标下方3行再包括本身1行，共4行。

ndd：若按3dd键，表示删除当前光标位置的1行和下面的2行。

x：删除光标所在位置的字符

X：删除光标所在位置的前一个字符，与d+←键一样

nx：按4x键，表示删除光标位置后的3个字符和光标本身所在的字符

nX：按4X键，表示删除光标位置之前的4个字符（不包括光标的字符）

查找及替换文字

/或？：当药搜索文章中的某一个字符串时，可输入“/”或“?”，然后在输入要查找的字符串。例如输入“/kuka”，然后按回车键，vim就会把所有的gz字符串标记起来，并自动将光标移到第一个找到的字符串上。

n：将光标移到下一个找到的字符串上

N：将光标移到上一个找到的字符串上

r：替换光标所在的位置的字符。修改内容不一定要进入insert mode，在normal mode中，只要将光标移到要更改的字符上，然后按R键，就可以输入要查找的字符了。

R：连续替换光标所在的位置的字符，按Esc键停止替换

cc：按cc键可以替换光标所在的那一行

替换字符串：当要将文章中的某一个字符串全部替换时（例如将所有的temp替换成tmp），使用“:g/temp/s//tmp/g”或“:1,$stemp/tmp /g”命令，可立刻将所有的“temp”替换成“tmp”字符串。如果不是所有的“temp”字符串都要替换时，可用“:g/temp/s//tmp /gc”或“:1/,$stemp/tmp/gc”命令。则找到每一个“temp”字符串时，都会将整行显示在屏幕的下方，可输入“y”或“n”决定是否要替换。

显示光标所在的行数、移到指定的行数

^g、^G：按次组合键，则会在最下方处显示光标所造位置的行数，以及文章的总行数。

nG：n为数字，若按下20G，则可将光标移到第20行。

还原

u：按此键就是在执行undo命令，可取消前一次的操作

^r：按此键就是执行redo命令，可以恢复刚才undo的操作



* gpic

[[http://www.ibm.com/developerworks/cn/linux/l-gnuplot/index.html][gnuplot 让您的数据可视化]]


[[http://www.math.uiuc.edu/~west/gpic.html][Drawing Graphs with gpic - Douglas B. West]]

http://plan9.bell-labs.com/sys/man/index.html


[[https://bespin.mozilla.com/][Web Eclipse]]

* SQLUnit

http://sqlunit.sourceforge.net/


* Chrome

http://www.it.com.cn/edu/tools/nettools/2009/10/14/18/646158.html


* firefox

** [[https://addons.mozilla.org/zh-CN/firefox/addon/59133/][Ease Link]]

** [[https://addons.mozilla.org/zh-CN/firefox/addon/190][Linkification]]

** [[https://addons.mozilla.org/en-US/firefox/addon/reloadevery/][ReloadEvery]]

** plugins

  1. http://www.delicious.com/
  2. http://getfirebug.com/
  3. http://www.getforecastfox.com/
  4. http://yellow5.us/firefox/linkification/
  5. https://addons.mozilla.org/en-US/firefox/addon/161916/
  6. RSS  https://addons.mozilla.org/zh-CN/firefox/addon/rss-ticker/?#+BEGIN_SRC 


* Chrome

** plugin

 1. https://chrome.google.com/extensions/detail/flcpelgcagfhfoegekianiofphddckof?hl=en



* [[http://mozillalabs.com/skywriter/2011/01/18/mozilla-skywriter-has-been-merged-into-ace/][ ACE ]] bespin

https://bespin.mozillalabs.com/

https://mozillalabs.com/bespin/

https://wiki.mozilla.org/Labs/Bespin/DeveloperGuide/Setup

* [[http://www.yworks.com/en/products_yed_about.html][yEd Graph Editor]]

yEd is a powerful diagram editor that can be used to quickly and effectively generate high-quality drawings of diagrams. 


* Firebug Lite

http://getfirebug.com/firebuglite#Stable 


* [[http://nevernote.sourceforge.net/index.htm][NeverNote]]

Welcome to NeverNoteThis is an open source clone of Evernote. This program has been run on Linux, Windows, and OS-X, but the
primary goal is to proved a Linux client.  While this is designed to work with Evernote, it is in no way connectedwith or
supported by Evernote.  Any problems you encounter will not be corrected by them and,since this is GPL software, you are using
this software at your own risk.People have used this with both 64 & 32 bit versions of Linux as well as OpenJDK & Sun's Java
and(so far) have not encountered any problems with these different environments.You can download NeverNote here.  All the
installation information as well as known problemsand currently supported features are located within this public notebook. 


* [[http://voicechatter.org/quickstart.php][Voice Chatter]]

 Btsjazz server

 Port: 7887

 admin password: pass4admin
 client password: pass4jazz


*  [[http://code.google.com/p/telluriumdoc/wiki/html/TelluriumQuickStart][Tellurium是一个开源的网页测试框架]]
 

mvn archetype:create -DgroupId=example -DartifactId=demo -DarchetypeArtifactId=tellurium-junit-archetype -DarchetypeGroupId=tellurium -DarchetypeVersion=0.6.0  -DarchetypeRepository=http://kungfuters.org/nexus/content/repositories/releases


* yED

draw pic. 

* google

#+BEGIN_SRC
google已经成为一个不可或缺的搜索工具，每天被数百万人使用，并渗透到生活的所有层面。无论是工作或学习、研究、寻找电影以及名人的八卦新闻。 
本文介绍了20条简单有趣的技巧，让你告别以往费时费力的搜索习惯。

对上百万人而言，Google是一个每天都要用到的、生活各方面都要用上的不可或缺的搜索工具。从工作、学校、研究、到查找电影、名人、新闻、八卦，Google是一个万事通型的搜索引擎。 
除了仅仅输入一个词组然后费力地在一页又一页的搜索结果里查找答案，还有一些方法能让你的搜索更加有效。

这些方法中，有些是众所周知的，你也可能了解的。但有些方法不为人熟知，还有些是大家知道但很少用上的。本文将让你了解更多或记起一些这种能更快更准确地找到答案的最佳方法。
或。Google通常会查找搜索框内输入的所有字词都包含的页面，但如果你希望页面里只含有这个或那个词（或者两个都有），就要用´OR´操作符或者用¡|´符号（管道符号），这样可以少敲几次键盘。例如[dumb | little | man]。
双引号。如果你希望精确搜索一个短语，给它加上双引号。["dumb little man"]会查出只包含整个词组的页面。[dumb "little man"]则会列出包含dumb这个词和"little man"这个词组的页面。
不包含。如果你不需要某个词或词组，在它前面加上´-¡号。[-dumb little man]会返回包含´little"和"man"但不包含"dumb"的页面。
近义词。使用´~¡号可以返回意义相近的词语。[~dumb little man -dumb]可得到包含´funny little man"和"stupid little man"但不包含´dumb little man"的页面。
通配符。´*¡号是一个通配符。如果你想查找一首歌的歌词，但记不起具体的歌词时这个方法很有用。 [can't * me love lyrics]会返回你要查找的披头士的歌词。另外当你希望只在某个领域（如教育类信息）中搜索时也可以用这个方法：["dumb little man" research *.edu]
高级搜索。如果你记不住这些操作符，你还可以随时使用Google的高级搜索。
定义。使用´define:"操作符可以快速地得到某个字词的定义。[define:dumb]会给你列出一大堆对´dumb"这个词的来自各种链接的定义。
计算器。这是Google最方便的用法之一，在搜索框里输入一条算式就可以很快地得到计算结果。大多数时候比你调用电脑里的计算器程序还要快。用+、-、*、/这些符号和括号就可以做出一条算式。
数字范围搜索。这个不为人熟知的技巧是用来对某个范围的数字进行搜索。例如，["best books 2002..2007]会列出2002年到2007年间每年最好的书（注意两个数字间有两个英文句号）。
站内搜索。使用´site:"操作符可以只在指定网站内搜索。[site:dumblittleman.com leo]会只在这个网站里查找包含´leo´这个词的页面。
反向链接。´link:"操作符可以查出链接至某个网址（URL）的页面。你可以用来查某个主网址，甚至是某个特定的网页。但并不是所有的反向链接都会列出。
垂直搜索。这个技巧是用来在某个专业领域内，而不是在网络上所有网页里搜索。Google提供了几种特定搜索的方法，可以在博客、新闻、图书等领域内搜索：

电影。使用"movie:"操作符可以查找电影字幕，如果加上邮政编码或美国的城市名和州名还可得到在该地区的电影院名单和电影放映时间。
音乐。"music:"操作符可以返回只与音乐相关的内容。
单位换算。用Google可以做快速的换算，比如将码换算成米，或不同货币间的换算：[12 meters in yards]。
数字类型：Google的算法可以识别你输入的数字类型，所以你可以搜索：
电话区号
车辆识别码（仅适用于美国）
联邦通讯委员会（FCC）设备编码（仅适用于美国）
环球产品代码（UPC）
联邦航空管理局（FAA）飞机登记号（仅适用于美国）
专利号（仅适用于美国）
甚至是股票价格（使用股票代码）或最近五天的天气预报
文件类型。例如，如果你只想查找.PDF文件、Word文档、或EXCEL表格，就可以使用"filetype:"操作符。
关键词位置。默认情况下，Google会在整个网页里查找你的关键词。但如果你只想在某个位置里查找，就要用 到"inurl:"、´intitle:"、"intext:"和"inanchor:"这些操作符。它们能让搜索只在网址、网页标题、主体文本和链接锚 文本（用于描述链接的文本）里进行。
缓存页面。查找Google在其服务器上存储的某个页面的版本？这个技巧可以帮你查找以前的或更新的页面：使用"cached:"操作符。
生命、宇宙及任何事物的终极答案。用小写字母输入这个短语(Answer to life, the universe, and everything)

#+END_SRC








* Nginx


 - [[http://tengine.taobao.org/book/][Nginx开发从入门到精通]]


