#author Will Chang
#title Version control

<contents>

* SVN

http://www.subversion.org.cn/svnbook/

** web svn

http://www.sventon.org/


* CVS

** CVS merge

http://wiki.aasimon.org/doku.php?id=cvs:merge


* hg 

[[http://hgbook.red-bean.com/][Mercurial: The Definitive Guide by Bryan O'Sullivan]]

http://wiki.alliedmods.net/Mercurial_Tutorial

 [[http://hgbook.red-bean.com/read/a-tour-of-mercurial-merging-work.html][Mercurial: The Definitive Guide]]

* [[http://www.javaforge.com/project/HGE][MercurialEclipse]]

MercurialEclipse is a plugin providing support for the highly popular Mercurial distributed version control system within the Eclipse IDE.

MercurialEclipse supports:

    * cloning repositories and importing them as Eclipse projects
    * push, pull and convenient syncronization
    * working with branches (branch, merge and rebase)
    * tags
    * undo (backout, rollback and strip)
    * diffs
    * histories
    * patches
    * Mercurial extensions (mqueue, transplant and such) 


** Big file

 http://mercurial.selenic.com/wiki/BigfilesExtension

 http://mercurial.selenic.com/wiki/HandlingLargeFiles

Usage

  1. 'hg add', ignoring the size warning.
  2. hg bstat
  3. hg bupdate

<src>
    * The extension overrides 'hg update', so that it can compare contents of '.bigfiles' before and after the update to remove and fetch appropriate big files.
    * The directory storing versions of big files can be synced with the remote one (the extension doesn't do this, but tells the list of the necessary files). The versions corresponding to old changesets can be removed to save space.
    * To add a new big file, use normal 'hg add', ignoring the size warning.
    * To remove a tracked big file, just delete it.
    * 'hg bstatus' - to examine state of big files in working directory.
    * 'hg brefresh' - to refresh '.bigfiles' and versions directory with added,
          o removed and modified big files. 
    * 'hg bupdate' - to fetch files from versions directory as recorded in
          o '.bigfiles', and get a list of necessary files missing in the version directory. 
</src>
Configuration

Configure your .hgrc to enable the extension by adding following lines:
<src>
[extensions]
bigfiles = path/to/bigfiles.py

[bigfiles]
repo = path/to/versions/dir 
</src>

** How to manage my files with hg


home  with branch cygwin and ubuntu

 ---ideas with branch idea

I think I need  project --- ideas. 

The project "will" is related with os: ubuntu, cygwin and windows. I can pull the will in cygwin from desktop to laptop. So I can
backup will project.

The project "ideas" on laptop should be same with the one on desktop. 

I can write a shell script to start the will project on port 8000 and ideas project on 8002, then I pull all them to desktop to
backup the data.

** Branch and tags


  hg clone myproject myproject-merge

  hg branches

  hg branch foo






* [[http://pypi.python.org/pypi/hgsvn][hgsvn]]

<src>
$ mkdir nose && cd nose
  # Make SVN checkout, initialize hg repository with first SVN revision
$ hgimportsvn http://python-nose.googlecode.com/svn/trunk
hgimportsvn svn://changwei.dyn.webahead.ibm.com
$ cd trunk
  # Pull all history from SVN, creating a new hg changeset for each SVN rev
$ hgpullsvn

</src>

* My Projects layout

There should be three type of project. 

One is the configurations, this is for the different system.Usually, it should be the home folder.

Another is the source code they are platform independent. But need some branches.

The last on is the documentation and books. They just need update, and need not worry about the platform or version. 

<src>

-ideas  所有的个人项目，需要使用 hg 进行版本管理
-- projectA
---    win
---    cygwin
---    ubuntu

-netsyncdisc  网络同步盘 个人文档，图书，个人开发项目使用的工具
-- books
-- software
-- openSourceProjects

-work 暂定，存放公司项目开发的代码，文档和工具。

</src>
	
* subversion 	
* 1 create repos


<src>
$ svnadmin create /path/to/repos
$ ls /path/to/repos
conf/  dav/  db/  format  hooks/  locks/  README.txt



/tmp/project/branches/
/tmp/project/tags/
/tmp/project/trunk/
               foo.c
               bar.c
               Makefile
               ¡­

</src>

* 2 Import projects


<src>

svn mkdir svn://changwei.dyn.webahead.ibm.com/bin/ubuntu  -m "init mk"

svn co -N  svn://changwei.dyn.webahead.ibm.com/bin/ubuntu  bin

svn import eu4db  svn://www.standino.com/trunk/standino/ideas/eu4db/ -m "initial import"

svn import Will  svn://www.standino.com/cygwin/trunk/Will/ -m "initial import"

svn import software svn://www.standino.com/software/trunk/ -m "initial import"

svn co -N svn://www.standino.com/software/trunk/ software

svn checkout -N svn://www.standino.com/trunk/standino/
Checked out revision 10.

svn co svn://www.standino.com/cygwin/trunk/Will/

cd c:\standino


svn cp svn://www.standino.com/trunk/standino/ideas/myscripts/emacs
svn://www.standino.com/cygwin/trunk/Will/ideas/emacs -m "move emacs to
a high level"

will@will-laptop:~/ideas/newlogistics$ svn mv https://newlogistics.googlecode.com/svn/trunk/logistics  https://newlogistics.googlecode.com/svn/branches/log_0_1 -m "bakup old code"


</src>

* Export repos

svn export file:///c:/archive/svn/repository my-export20080505

* Check out project 

svn co svn://www.standino.com/trunk/standino/ideas/eu4db/ 

* View log
svn log -v

* view the old file

<src>
svn cat --revision 2 rules.txt 
</src>

* EXTERNAL

C:\standino\ideas>svn propedit svn:externals .


C:\standino\ideas\logistics\web\src\main\jsp>svn propset svn:externals "dojo_trunk
http://svn.dojotoolkit.org/dojo/view/anon/all/trunk" dojo

logic.war https://newlogistics.googlecode.com/svn/new

logistics  https://newlogistics.googlecode.com/svn/trunk

* Make a branch 

* Using emacs as editor

update .bahrc

<src>

export EDITOR="emacs-nox.exe -q"

</src>





* svn export — Export a clean directory tree.

<example>
Synopsis

svn export [-r REV] URL [PATH]

svn export PATH1 PATH2

Description

The first form exports a clean directory tree from the repository specified by URL, at revision REV if it is given, otherwise at HEAD, into PATH. If PATH is omitted, the last component of the URL is used for the local directory name.

The second form exports a clean directory tree from the working copy specified by PATH1 into PATH2. All local changes will be preserved, but files not under version control will not be copied.
Alternate Names

None
Changes

Local disk
Accesses Repository

Only if exporting from a URL
Switches

--revision (-r) REV
--quiet (-q)
--force
--username USER
--password PASS
--no-auth-cache
--non-interactive
--config-dir DIR

Examples

Export from your working copy (doesn't print every file and directory):

$ svn export a-wc my-export
Export complete.

Export directly from the repository (prints every file and directory):

$ svn export file:///tmp/repos my-export
A  my-export/test
A  my-export/quiz
…
Exported revision 15.
</example>


* Cygwin环境下使用Subversion和SSH (Not verified)

Subversion既可以和Apache相结合通过http协议存取，也可以通过ssh协议来存取。本文主要介绍在Cygwin下如何配置Subversion和SSH服务器。

** 配置SSH服务器

首先从http://www.cygwin.com下载Cygwin安装程序，安装过程中一定要选择以下包，其他安装包可以根据需要来选择。

Admin->cygrunsrv
Devel->subversion
Net->openssh

Cygwin安装完毕后，接着配置sshd服务器，在Cygwin Shell中运行命令：

ssh-host-config -y

提示”CYGWIN=”时输入：

tty ntsec

至此，ssh服务器已经配置完毕，可以通过Windows服务管理器来启动或停止ssh服务，也可以通过命令行 net [start|stop] sshd来控制。

** 配置访问Svbversion服务器

Subversion的具体使用方法可以参考[[http://www.subversion.org.cn/svnbook/][使用手册]]。通过ssh访问SubVersion的方法：

svn co svn+ssh://servername/project

其他任何机器都可以通过ssh客户端来访问此Subversion服务器，用户名和密码就是这台Windows系统的用户名和密码。如果不想输入用户名和密码，可以通过配置SSH的密钥验证来实现。


* Git

[[http://git.or.cz/course/svn.html][Git - SVN Crash Course]]

[[http://eagain.net/articles/git-for-computer-scientists/][Tv's cobweb: Git for Computer Scientists]]

[[http://github.com/][git repository hosting]]

[[http://xtalk.msk.su/~ott/en/writings/emacs-vcs/EmacsGit.html][Work with Git from Emacs]]

如果发现git status 发现所有的中文文件名被换成\123\223\145\333.doc文件时，可以使用

 git config --global core.quotepath false

* SVN Layout

<example>
www.standino.com/
                mp3
                book
                software/trunk
</example>

* HG

** 方便的安装。
不论是mac, linux还是windows，不论你是命令行的爱好者还是乌龟的忠实粉丝，你总能找到一款适合你的。

** 2个命令创建一个Mercuria仓库，
> hg init
> hg serve，
通过这两个命令你就可以拥有一个通过HTTP协议访问的mercurial仓库， 你可以方便的通过客户端通过命令访问，或者你可以轻松的使用浏览器来浏览当前的代码。

** 方便的分布式功能
上一次在印度我想在一台新电脑上安装源代码，无奈网络速度太慢，于是乎，我找到一个存有源码的机器，hg serve，这样我得到了一个本地服务器，通过它，我在1分钟内拿到了代码，然后将hgrc(一个mercurial的配置文件)的URL指向在中国的服务器，继续更新后面的几个patch。 将一个1个小时的操作变成2分钟的操作。

如果你急需要某个patch, 但是你的同事还没来得及提交到服务器上去，没关系，你大可以将自己的workingcopy指向同事的电脑， 运行hg pull就可以从他那里及时的拿到最新的代码。

没有branch的痛苦, 没有branch是因为每个人都是一个branch -_-!!!

** 便捷的本地提交
使用Mercurial，你可以在没有网络的情况下通过
> hg ci
进行本地提交，再也无需因为没有网络时候患上“写代码没有SCM恐惧症”，你也可以通过这个命令在日常开发中即达到小步前进，又不用每10分钟非得跑一遍测试。

** 离线操作
不论是Mercurial的提交或者是diff，rollback，strip, merge都可以在没有网络的情况下进行，想像一下在中国开发，服务器在美国的痛苦：那缓慢爬行的小乌龟。

** 速度优势
Mercurial是增量存储，并且它会每隔一段时间进行对整个Repository打一个快照，这样当你去clone repository(相当于svn checkout)的时候，它可以找到最近的一个快照，并在它的基础上应用后续的patch。

** 基于patch的管理
Mercurial将你的提交作为一个patch管理， 你可以很容易拿到别人的patch，通过hg客户端或者linux上的 patch命令将别人最新的修正打在你的工作目录里面。

** 更多的便捷操作
你想将本地的某些提交取消? hg strip
你想将server上的某些changeset取消？hg backout
你想订制hg log的输出方式？定义自己的hg template。


这个工具在国内很少人使用，所以中文资料匮乏．只有官方的website上有一些少得可怜的中文资料了．不过总体上来说，hg还是比较好用的。

这里绍一下hg服务器的配置。关于hg在基本用法参见mercrial的官方网站。在做以下操作时，请到 http://www.selenic.com/mercurial/下载安装hg.

1.建立用户hgrepo

其它用户将用这个账户用hg服务器push代码。

useradd hgrepo -d /home/hgrepo # add user hgrepo
passwd hgrepo

2.建立hg代码仓库

如果代码仓库名称为project.hg,则可用如下命令。

cd /home/hgrepo
mkdir project.hg
cd project.hg
hg init # 初始化代码仓库
建立一个测试文件

echo "hello, mercurial" > sample.txt
hg add  # add
hg ci     # check in

3. 打开http

打开一个端口，让远程用户可以clone仓库中的代码.
在打开端口前请确定文件权限正确。

更改文件权限
chown hgrepo.hgrepo /home/hgrepo/project.hg -R
chmod og+rw /home/hgrepo/project.hg -R
打开端口

cd  /home/hgrepo/project.hg -R
hg serve -p 8002 &
可将上面两行加入/etc/rc.local这样就可以在开机的时候自动运行了。

4.使用hg

完成步骤3以后，我们就可以使用了。

clone到本地

例如你的服务器的名字为test.

hg clone http://test:8002
然后在本地目录就会出现一个project.hg的一个copy.

修改Client端的配置

更改.hg/hgrc，加上default-push和username
<src>
[paths]
default = http://test:8002
default-push = ssh://hgrepo@test//home/hgrepo/project.hg/
[ui]
username=shaohui.zheng

[paths]
default = http://9.123.157.55:8000
default-push = ssh://will@9.123.157.55//home/will/ideas/
default-push = https://standino@bitbucket.org/standino/my-private-rep


[ui]
username=will

</src>
这样你就可用hg push 向服务器提交code了。这时服务器会问你passward,这个password就是用户hgrepo的password.

Good Luck.

* My setup

hg clone http://changweilaptop.dyn.webahead.ibm.com:8000/ ideas


hg clone http://9.186.119.53:8000/ ideas

* How to use Emacs to work with Mercurial

http://xtalk.msk.su/~ott/en/writings/emacs-vcs/EmacsMercurial.html


** revert files

hg revert .amsn/ -r 385

首先，使用hg grep找到被删除的文件恢复。此命令的输出将显示该文件的最新版本是目前的，以及对已删除文件的路径。二，运行hg revert -r
<revision number> <path to deleted file>被删除的文件现在在你的工作拷贝，准备送回头部。  

* My remote Hg repository https://bitbucket.org/

 hg push https://standino@bitbucket.org/standino/my-private-rep


** 4.2. How to declare trust

Users can add settings to their $HOME/.hgrc to tell Mercurial to trust other users. For instance, if Bob has decided he can trust Alice not to try to delete his files when he looks at her repository, he could add:

[trusted]
users = alice, carl, dan

Alternately, Bob can decide to trust a group of people (as specified in an operating system group)

[trusted]
groups = dev-team


* 比较两个 branch 

http://stackoverflow.com/questions/4731190/how-to-show-the-diff-specific-to-a-named-branch-in-mercurial


<src>
  109  hg branches
  110  hg branch
  111  hg branch '多维度设置采购计划控制参数'
  112  hg branch
  113  hg bookmark '多维度设置采购计划控制参数'
  114  hg bookmark '多维度设置采购计划控制参数init'
  115  hg branchdiff .
  116  hg st
  117  hg branchdiff .
  118  hg ci -m "测试branch之间的比较"
  119  hg branchdiff .
  120  hg update default
  121  hg branches
  126  hg merge  '多维度设置采购计划控制参数'
</src>

In your specific example I think you could get a list of of just d and e using:

hg log -r "branch('foo') - branch('default')"
where that - is defined as:

"x - y"
      Changesets in x but not in y.
Getting the diff from a to e could be done as:

hg diff -r "ancestor(default, foo)" -r foo


Another way to do this, useful also for branches that you have already merged to default is:

hg diff -r "max(ancestors(foo) and branch(default)):foo"
Though that can be a pit of a pain, so i'd recommend setting up an alias by adding something like:

[alias]
branchdiff = diff -r "max(ancestors('$1') and branch(default)):'$1'"
To your Mercurial.INI/hgrc which you can then use like this:

hg branchdiff <branch name>
or

hg branchdiff .


