#+TITLE:       版本管理工具
#+AUTHOR:      Will Chang
#+EMAIL:       changwei.cn@gmail.com
#+DATE:        2013-12-19 Thu
#+URI:         /wiki/html/vesionmanage
#+KEYWORDS:    svn,cvs,git,hg
#+TAGS:        :svn:cvs:git:hg:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION:  Version control



* SVN

 - http://www.subversion.org.cn/svnbook/

** web svn

http://www.sventon.org/


** 设置忽略

  1. http://www.111cn.net/sys/linux/53797.htm

#+BEGIN_SRC
 export EDITOR=gedit
 svn propedit svn:ignore .
#+END_SRC

** 分支和tag

   - http://blog.csdn.net/yangzhongxuan/article/details/7519948
   - http://zccst.iteye.com/blog/1430823
   - http://www.panweizeng.com/svn-branching-merging.html
   -
** 合并

#+BEGIN_SRC
svn merge -r 44324:44325 http://svn.
#+END_SRC

** 1 create repos


#+BEGIN_SRC

$ svnadmin create /path/to/repos
$ ls /path/to/repos
conf/  dav/  db/  format  hooks/  locks/  README.txt



/tmp/project/branches/
/tmp/project/tags/
/tmp/project/trunk/
               foo.c
               bar.c
               Makefile
               ¡­

#+END_SRC

** 2 Import projects


<#+BEGIN_SRC >

svn mkdir svn://changwei.dyn.webahead.ibm.com/bin/ubuntu  -m "init mk"

svn co -N  svn://changwei.dyn.webahead.ibm.com/bin/ubuntu  bin

svn import eu4db  svn://www.standino.com/trunk/standino/ideas/eu4db/ -m "initial import"

svn import Will  svn://www.standino.com/cygwin/trunk/Will/ -m "initial import"

svn import software svn://www.standino.com/software/trunk/ -m "initial import"

svn co -N svn://www.standino.com/software/trunk/ software

svn checkout -N svn://www.standino.com/trunk/standino/
Checked out revision 10.

svn co svn://www.standino.com/cygwin/trunk/Will/

cd c:\standino


svn cp svn://www.standino.com/trunk/standino/ideas/myscripts/emacs
svn://www.standino.com/cygwin/trunk/Will/ideas/emacs -m "move emacs to
a high level"

will@will-laptop:~/ideas/newlogistics$ svn mv https://newlogistics.googlecode.com/svn/trunk/logistics  https://newlogistics.googlecode.com/svn/branches/log_0_1 -m "bakup old code"


#+END_SRC

** Export repos

svn export file:///c:/archive/svn/repository my-export20080505

** Check out project

svn co svn://www.standino.com/trunk/standino/ideas/eu4db/

** View log
svn log -v

** view the old file

<#+BEGIN_SRC >
svn cat --revision 2 rules.txt
#+END_SRC

** EXTERNAL

C:\standino\ideas>svn propedit svn:externals .

C:\standino\ideas\logistics\web\src
http://svn.dojotoolkit.org/dojo/view/anon/all/trunk" dojo

logic.war https://newlogistics.googlecode.com/svn/new

logistics  https://newlogistics.googlecode.com/svn/trunk

** svn export — Export a clean directory tree.

#+BEGIN_SRC
Synopsis

svn export [-r REV] URL [PATH]

svn export PATH1 PATH2

Description

The first form exports a clean directory tree from the repository specified by URL, at revision REV if it is given, otherwise at HEAD, into PATH. If PATH is omitted, the last component of the URL is used for the local directory name.

The second form exports a clean directory tree from the working copy specified by PATH1 into PATH2. All local changes will be preserved, but files not under version control will not be copied.
Alternate Names

None
Changes

Local disk
Accesses Repository

Only if exporting from a URL
Switches

--revision (-r) REV
--quiet (-q)
--force
--username USER
--password PASS
--no-auth-cache
--non-interactive
--config-dir DIR

Examples

Export from your working copy (doesn't print every file and directory):

$ svn export a-wc my-export
Export complete.

Export directly from the repository (prints every file and directory):

$ svn export file:///tmp/repos my-export
A  my-export/test
A  my-export/quiz
…
Exported revision 15.
#+END_SRC


** Cygwin环境下使用Subversion和SSH (Not verified)

Subversion既可以和Apache相结合通过http协议存取，也可以通过ssh协议来存取。本文主要介绍在Cygwin下如何配置Subversion和SSH服务器。

*** 配置SSH服务器

首先从http://www.cygwin.com下载Cygwin安装程序，安装过程中一定要选择以下包，其他安装包可以根据需要来选择。

Admin->cygrunsrv
Devel->subversion
Net->openssh

Cygwin安装完毕后，接着配置sshd服务器，在Cygwin Shell中运行命令：

ssh-host-config -y

提示”CYGWIN=”时输入：

tty ntsec

至此，ssh服务器已经配置完毕，可以通过Windows服务管理器来启动或停止ssh服务，也可以通过命令行 net [start|stop] sshd来控制。

*** 配置访问Svbversion服务器

Subversion的具体使用方法可以参考[[http://www.subversion.org.cn/svnbook/][使用手册]]。通过ssh访问SubVersion的方法：

svn co svn+ssh://servername/project

其他任何机器都可以通过ssh客户端来访问此Subversion服务器，用户名和密码就是这台Windows系统的用户名和密码。如果不想输入用户名和密码，可以通过配置SSH的密钥验证来实现。

** Linux 下svn恢复到某一版本

  - http://blog.163.com/xiaoy2002@126/blog/static/679795342012811102449474/ 

* Git

 - [[http://git.or.cz/course/svn.html][Git - SVN Crash Course]]
 - [[http://eagain.net/articles/git-for-computer-scientists/][Tv's cobweb: Git for Computer Scientists]]
 - [[http://github.com/][git repository hosting]]
 - [[http://xtalk.msk.su/~ott/en/writings/emacs-vcs/EmacsGit.html][Work with Git from Emacs]]

如果发现git status 发现所有的中文文件名被换成\123\223\145\333.doc文件时，可以使用

 git config --global core.quotepath false

** DONE 子模块
   CLOSED: [2014-03-31 一 11:05]
   - State "DONE"       from "OKTODAY"    [2014-03-31 一 11:05]
   - State "OKTODAY"    from "STARTED"    [2014-03-31 一 11:05]
   :LOGBOOK:
   CLOCK: [2014-03-31 一 10:33]--[2014-03-31 一 11:05] =>  0:32
   :END:


 2. http://aoxuis.me/posts/2013/08/07/git-subtree/
 3. http://ruby-china.org/topics/13001
 1. http://git-scm.com/book/zh/Git-%E5%B7%A5%E5%85%B7-%E5%AD%90%E6%A8%A1%E5%9D%97

#+BEGIN_SRC

git clone https://github.com/standino/easy-portal.git

cd easy-portal/

git remote add -f jquery-ui-portlet https://github.com/standino/jquery-ui-portlet.git

git subtree add --prefix=src/main/webapp/resources/jquery-ui-portlet jquery-ui-portlet master --squash

#+END_SRC

** [[http://blog.csdn.net/ithomer/article/details/7529841][本文将对Git 命令，做一下全面而系统的简短总结，整理成简洁、明了的图表结构，方便查询]]

一、 Git 常用命令速查
git branch 查看本地所有分支
git status 查看当前状态
git commit 提交
git branch -a 查看所有的分支
git branch -r 查看远程所有分支
git commit -am "init" 提交并且加注释
git remote add origin git@192.168.1.119:ndshow
git push origin master 将文件给推到服务器上
git remote show origin 显示远程库origin里的资源
git push origin master:develop
git push origin master:hb-dev 将本地库与服务器上的库进行关联
git checkout --track origin/dev 切换到远程dev分支
git branch -D master develop 删除本地库develop
git checkout -b dev 建立一个新的本地分支dev
git merge origin/dev 将分支dev与当前分支进行合并
git checkout dev 切换到本地dev分支
git remote show 查看远程库
git add .
git rm 文件名(包括路径) 从git中删除指定文件
git clone git://github.com/schacon/grit.git 从服务器上将代码给拉下来
git config --list 看所有用户
git ls-files 看已经被提交的
git rm [file name] 删除一个文件
git commit -a 提交当前repos的所有的改变
git add [file name] 添加一个文件到git index
git commit -v 当你用－v参数的时候可以看commit的差异
git commit -m "This is the message describing the commit" 添加commit信息
git commit -a -a是代表add，把所有的change加到git index里然后再commit
git commit -a -v 一般提交命令
git log 看你commit的日志
git diff 查看尚未暂存的更新
git rm a.a 移除文件(从暂存区和工作区中删除)
git rm --cached a.a 移除文件(只从暂存区中删除)
git commit -m "remove" 移除文件(从Git中删除)
git rm -f a.a 强行移除修改后文件(从暂存区和工作区中删除)
git diff --cached 或 $ git diff --staged 查看尚未提交的更新
git stash push 将文件给push到一个临时空间中
git stash pop 将文件从临时空间pop下来
---------------------------------------------------------
git remote add origin git@github.com:username/Hello-World.git
git push origin master 将本地项目给提交到服务器中
-----------------------------------------------------------
git pull 本地与服务器端同步
-----------------------------------------------------------------
git push (远程仓库名) (分支名) 将本地分支推送到服务器上去。
git push origin serverfix:awesomebranch
------------------------------------------------------------------
git fetch 相当于是从远程获取最新版本到本地，不会自动merge
git commit -a -m "log_message" (-a是提交所有改动，-m是加入log信息) 本地修改同步至服务器端 ：
git branch branch_0.1 master 从主分支master创建branch_0.1分支
git branch -m branch_0.1 branch_1.0 将branch_0.1重命名为branch_1.0
git checkout branch_1.0/master 切换到branch_1.0/master分支
du -hs

git branch 删除远程branch
git push origin :branch_remote_name
git branch -r -d branch_remote_name

-----------------------------------------------------------
初始化版本库，并提交到远程服务器端
mkdir WebApp
cd WebApp
git init                                本地初始化
touch README
git add README          添加文件
git commit -m 'first commit'
git remote add origin git@github.com:daixu/WebApp.git   增加一个远程服务器端
上面的命令会增加URL地址为'git@github.com:daixu/WebApp.git'，名称为origin的远程服务器库，以后提交代码的时候只需要使用 origin别名即可


二、 Git 命令速查表

1、常用的Git命令
| 命令                   | 简要说明                                 |
| git add                | 添加至暂存区                             |
| git add–interactive    | 交互式添加                               |
| git apply              | 应用补丁                                 |
| git am                 | 应用邮件格式补丁                         |
| git annotate           | 同义词，等同于 git blame                 |
| git archive            | 文件归档打包                             |
| git bisect             | 二分查找                                 |
| git blame              | 文件逐行追溯                             |
| git branch             | 分支管理                                 |
| git cat-file           | 版本库对象研究工具                       |
| git checkout           | 检出到工作区、切换或创建分支             |
| git cherry-pick        | 提交拣选                                 |
| git citool             | 图形化提交，相当于 git gui 命令          |
| git clean              | 清除工作区未跟踪文件                     |
| git clone              | 克隆版本库                               |
| git commit             | 提交                                     |
| git config             | 查询和修改配置                           |
| git describe           | 通过里程碑直观地显示提交ID               |
| git diff               | 差异比较                                 |
| git difftool           | 调用图形化差异比较工具                   |
| git fetch              | 获取远程版本库的提交                     |
| git format-patch       | 创建邮件格式的补丁文件。参见 git am 命令 |
| git grep               | 文件内容搜索定位工具                     |
| git gui                | 基于Tcl/Tk的图形化工具，侧重提交等操作   |
| git help               | 帮助                                     |
| git init               | 版本库初始化                             |
| git init-db*           | 同义词，等同于 git init                  |
| git log                | 显示提交日志                             |
| git merge              | 分支合并                                 |
| git mergetool          | 图形化冲突解决                           |
| git mv                 | 重命名                                   |
| git pull               | 拉回远程版本库的提交                     |
| git push               | 推送至远程版本库                         |
| git rebase             | 分支变基                                 |
| git rebase–interactive | 交互式分支变基                           |
| git reflog             | 分支等引用变更记录管理                   |
| git remote             | 远程版本库管理                           |
| git repo-config*       | 同义词，等同于 git config                |
| git reset              | 重置改变分支“游标”指向                 |
| git rev-parse          | 将各种引用表示法转换为哈希值等           |
| git revert             | 反转提交                                 |
| git rm                 | 删除文件                                 |
| git show               | 显示各种类型的对象                       |
| git stage*             | 同义词，等同于 git add                   |
| git stash              | 保存和恢复进度                           |
| git status             | 显示工作区文件状态                       |
| git tag                | 里程碑管理                               |

2、对象库操作相关命令
| 命令             | 简要说明                             |
| git commit-tree  | 从树对象创建提交                     |
| git hash-object  | 从标准输入或文件计算哈希值或创建对象 |
| git ls-files     | 显示工作区和暂存区文件               |
| git ls-tree      | 显示树对象包含的文件                 |
| git mktag        | 读取标准输入创建一个里程碑对象       |
| git mktree       | 读取标准输入创建一个树对象           |
| git read-tree    | 读取树对象到暂存区                   |
| git update-index | 工作区内容注册到暂存区及暂存区管理   |
| git unpack-file  | 创建临时文件包含指定 blob 的内容     |
| git write-tree   | 从暂存区创建一个树对象               |

3、引用操作相关命令
| 命令                 | 简要说明                       |
| git check-ref-format | 检查引用名称是否符合规范       |
| git for-each-ref     | 引用迭代器，用于shell编程      |
| git ls-remote        | 显示远程版本库的引用           |
| git name-rev         | 将提交ID显示为友好名称         |
| git peek-remote*     | 过时命令，请使用 git ls-remote |
| git rev-list         | 显示版本范围                   |
| git show-branch      | 显示分支列表及拓扑关系         |
| git show-ref         | 显示本地引用                   |
| git symbolic-ref     | 显示或者设置符号引用           |
| git update-ref       | 更新引用的指向                 |
| git verify-tag       | 校验 GPG 签名的Tag             |

4、版本库管理相关命令
| 命令               | 简要说明                               |
| git count-objects  | 显示松散对象的数量和磁盘占用           |
| git filter-branch  | 版本库重构                             |
| git fsck           | 对象库完整性检查                       |
| git fsck-objects*  | 同义词，等同于 git fsck                |
| git gc             | 版本库存储优化                         |
| git index-pack     | 从打包文件创建对应的索引文件           |
| git lost-found*    | 过时，请使用 git fsck –lost-found 命令 |
| git pack-objects   | 从标准输入读入对象ID，打包到文件       |
| git pack-redundant | 查找多余的 pack 文件                   |
| git pack-refs      | 将引用打包到 .git/packed-refs 文件中   |
| git prune          | 从对象库删除过期对象                   |
| git prune-packed   | 将已经打包的松散对象删除               |
| git relink         | 为本地版本库中相同的对象建立硬连接     |
| git repack         | 将版本库未打包的松散对象打包           |
| git show-index     | 读取包的索引文件，显示打包文件中的内容 |
| git unpack-objects | 从打包文件释放文件                     |
| git verify-pack    | 校验对象库打包文件                     |
|                    |                                        |

5、数据传输相关命令
| 命令               | 简要说明                                                                            |
| git fetch-pack     | 执行 git fetch 或 git pull 命令时在本地执行此命令，用于从其他版本库获取缺失的对象   |
| git receive-pack   | 执行 git push 命令时在远程执行的命令，用于接受推送的数据                            |
| git send-pack      | 执行 git push 命令时在本地执行的命令，用于向其他版本库推送数据                      |
| git upload-archive | 执行 git archive –remote 命令基于远程版本库创建归档时，远程版本库执行此命令传送归档 |
| git upload-pack    | 执行 git fetch 或 git pull 命令时在远程执行此命令，将对象打包、上传                 |

6、邮件相关命令
| 命令               | 简要说明                                                                            |
| git imap-send      | 将补丁通过 IMAP 发送                                                                |
| git mailinfo       | 从邮件导出提交说明和补丁                                                            |
| git mailsplit      | 将 mbox 或 Maildir 格式邮箱中邮件逐一提取为文件                                     |
| git request-pull   | 创建包含提交间差异和执行PULL操作地址的信息                                          |
| git send-email     | 发送邮件                                                                            |

7、协议相关命令
| 命令                   | 简要说明                                    |
| git daemon             | 实现Git协议                                 |
| git http-backend       | 实现HTTP协议的CGI程序，支持智能HTTP协议     |
| git instaweb           | 即时启动浏览器通过 gitweb 浏览当前版本库    |
| git shell              | 受限制的shell，提供仅执行Git命令的SSH访问   |
| git update-server-info | 更新哑协议需要的辅助文件                    |
| git http-fetch         | 通过HTTP协议获取版本库                      |
| git http-push          | 通过HTTP/DAV协议推送                        |
| git remote-ext         | 由Git命令调用，通过外部命令提供扩展协议支持 |
| git remote-fd          | 由Git命令调用，使用文件描述符作为协议接口   |
| git remote-ftp         | 由Git命令调用，提供对FTP协议的支持          |
| git remote-ftps        | 由Git命令调用，提供对FTPS协议的支持         |
| git remote-http        | 由Git命令调用，提供对HTTP协议的支持         |
| git remote-https       | 由Git命令调用，提供对HTTPS协议的支持        |
| git remote-testgit     | 协议扩展示例脚本                            |

8、版本库转换和交互相关命令
| 命令                | 简要说明                                     |
| git archimport      | 导入Arch版本库到Git                          |
| git bundle          | 提交打包和解包，以便在不同版本库间传递       |
| git cvsexportcommit | 将Git的一个提交作为一个CVS检出               |
| git cvsimport       | 导入CVS版本库到Git。或者使用 cvs2git         |
| git cvsserver       | Git的CVS协议模拟器，可供CVS命令访问Git版本库 |
| git fast-export     | 将提交导出为 git-fast-import 格式            |
| git fast-import     | 其他版本库迁移至Git的通用工具                |
| git svn             | Git 作为前端操作 Subversion                  |

9、合并相关的辅助命令
| 命令                | 简要说明                                                      |
| git merge-base      | 供其他脚本调用，找到两个或多个提交最近的共同祖先              |
| git merge-file      | 针对文件的两个不同版本执行三向文件合并                        |
| git merge-index     | 对index中的冲突文件调用指定的冲突解决工具                     |
| git merge-octopus   | 合并两个以上分支。参见 git merge 的octopus合并策略            |
| git merge-one-file  | 由 git merge-index 调用的标准辅助程序                         |
| git merge-ours      | 合并使用本地版本，抛弃他人版本。参见 git merge 的ours合并策略 |
| git merge-recursive | 针对两个分支的三向合并。参见 git merge 的recursive合并策略    |
| git merge-resolve   | 针对两个分支的三向合并。参见 git merge 的resolve合并策略      |
| git merge-subtree   | 子树合并。参见 git merge 的 subtree 合并策略                  |
| git merge-tree      | 显式三向合并结果，不改变暂存区                                |
| git fmt-merge-msg   | 供执行合并操作的脚本调用，用于创建一个合并提交说明            |
| git rerere          | 重用所记录的冲突解决方案                                      |

10、 杂项
| 命令                  | 简要说明                                            |
| git bisect–helper     | 由 git bisect 命令调用，确认二分查找进度            |
| git check-attr        | 显示某个文件是否设置了某个属性                      |
| git checkout-index    | 从暂存区拷贝文件至工作区                            |
| git cherry            | 查找没有合并到上游的提交                            |
| git diff-files        | 比较暂存区和工作区，相当于 git diff –raw            |
| git diff-index        | 比较暂存区和版本库，相当于 git diff –cached –raw    |
| git diff-tree         | 比较两个树对象，相当于 git diff –raw A B            |
| git difftool–helper   | 由 git difftool 命令调用，默认要使用的差异比较工具  |
| git get-tar-commit-id | 从 git archive 创建的 tar 包中提取提交ID            |
| git gui–askpass       | 命令 git gui 的获取用户口令输入界面                 |
| git notes             | 提交评论管理                                        |
| git patch-id          | 补丁过滤行号和空白字符后生成补丁唯一ID              |
| git quiltimport       | 将Quilt补丁列表应用到当前分支                       |
| git replace           | 提交替换                                            |
| git shortlog          | 对 git log 的汇总输出，适合于产品发布说明           |
| git stripspace        | 删除空行，供其他脚本调用                            |
| git submodule         | 子模组管理                                          |
| git tar-tree          | 过时命令，请使用 git archive                        |
| git var               | 显示 Git 环境变量                                   |
| git web–browse        | 启动浏览器以查看目录或文件                          |
| git whatchanged       | 显示提交历史及每次提交的改动                        |
| git-mergetool–lib     | 包含于其他脚本中，提供合并/差异比较工具的选择和执行 |
| git-parse-remote      | 包含于其他脚本中，提供操作远程版本库的函数          |
| git-sh-setup          | 包含于其他脚本中，提供 shell 编程的函数库           |




** github 不需要用户名密码push

 - https://help.github.com/articles/generating-ssh-keys
 - https://help.github.com/articles/using-ssh-over-the-https-port

编辑SSH config文件，将连接端口改成443:
#+BEGIN_SRC 
$ gedit ~/.ssh/config
#+END_SRC

添加如下代码：
#+BEGIN_SRC 

Host github.com
User standino
Port 443
Hostname ssh.github.com

#+END_SRC

再试一下命令：
#+BEGIN_SRC 
chmod 700 config
git config --global url."https://".insteadOf git://
$ ssh -T git@github.com
#+END_SRC





** 如何使用 github
  - [[https://help.github.com/articles/fork-a-repo][Fork A Repo
]]

#+BEGIN_SRC sh

# Changes the active directory in the prompt to the newly cloned  directory

cd .emacs.d/

# Assigns the original repository to a remote called "upstream"

git remote add upstream https://github.com/purcell/emacs.d.git

# Pulls in changes not present in your local repository, without modifying your files

git fetch upstream

# Fetches any new changes from the original repository

git fetch upstream

# Merges any changes fetched into your working files

git merge upstream/master





#+END_SRC

** git submodule


git push --recurse-submodules=on-demand

git pull --recurse-submodules origin master

git submodule foreach git pull


The 'foreach' command can execute any arbitrary shell script. Two options to pull the very latest might be,

git submodule foreach git pull origin master
and,

git submodule foreach /path/to/some/cool/script.sh
That will iterate through all initialized submodules and run the given commands.

** git subtree 


  1. http://ruleant.blogspot.com/2013/06/git-subtree-module-with-gittrees-config.html
  2. http://stackoverflow.com/questions/3202674/procedure-for-cloning-git-repos-that-use-subtree

#+BEGIN_SRC 

$git subtree add --prefix=other_project \
     git://github.com/your_tree/your_project.git master
$git subtree push --prefix=other_project
$git subtree pull --prefix=other_project


he way that I have in the past re-created that relationship was by doing a subtree merge.

git pull -s subtree <lib> master
even if there is nothing to merge in/pull it should simply return without doing anything. Feel free to add --squash to the above pull so that you don't pull in any remote history.
#+END_SRC


** git 常用操作

  1. [[http://blog.csdn.net/jackystudio/article/details/12271839][【Git入门之六】远程仓库]]

* hg

[[http://hgbook.red-bean.com/][Mercurial: The Definitive Guide by Bryan O'Sullivan]]

http://wiki.alliedmods.net/Mercurial_Tutorial

 [[http://hgbook.red-bean.com/read/a-tour-of-mercurial-merging-work.html][Mercurial: The Definitive Guide]]

** [[http://www.javaforge.com/project/HGE][MercurialEclipse]]

MercurialEclipse is a plugin providing support for the highly popular Mercurial distributed version control system within the Eclipse IDE.

MercurialEclipse supports:

    * cloning repositories and importing them as Eclipse projects
    * push, pull and convenient syncronization
    * working with branches (branch, merge and rebase)
    * tags
    * undo (backout, rollback and strip)
    * diffs
    * histories
    * patches
    * Mercurial extensions (mqueue, transplant and such)


*** Big file！

 http://mercurial.selenic.com/wiki/html/BigfilesExtension

 http://mercurial.selenic.com/wiki/html/HandlingLargeFiles

Usage

  1. 'hg add', ignoring the size warning.
  2. hg bstat
  3. hg bupdate

<#+BEGIN_SRC >
    * The extension overrides 'hg update', so that it can compare contents of '.bigfiles' before and after the update to remove and fetch appropriate big files.
    * The directory storing versions of big files can be synced with the remote one (the extension doesn't do this, but tells the list of the necessary files). The versions corresponding to old changesets can be removed to save space.
    * To add a new big file, use normal 'hg add', ignoring the size warning.
    * To remove a tracked big file, just delete it.
    * 'hg bstatus' - to examine state of big files in working directory.
    * 'hg brefresh' - to refresh '.bigfiles' and versions directory with added,
          o removed and modified big files.
    * 'hg bupdate' - to fetch files from versions directory as recorded in
          o '.bigfiles', and get a list of necessary files missing in the version directory.
#+END_SRC
Configuration

Configure your .hgrc to enable the extension by adding following lines:
<#+BEGIN_SRC >
[extensions]
bigfiles = path/to/bigfiles.py

[bigfiles]
repo = path/to/versions/dir
#+END_SRC

*** How to manage my files with hg


home  with branch cygwin and ubuntu

 ---ideas with branch idea

I think I need  project --- ideas.

The project "will" is related with os: ubuntu, cygwin and windows. I can pull the will in cygwin from desktop to laptop. So I can
backup will project.

The project "ideas" on laptop should be same with the one on desktop.

I can write a shell script to start the will project on port 8000 and ideas project on 8002, then I pull all them to desktop to
backup the data.

*** Branch and tags


   hg clone myproject myproject-merge

   hg branches

   hg branch foo





   
** [[http://pypi.python.org/pypi/hgsvn][hgsvn]]

<#+BEGIN_SRC >
$ mkdir nose && cd nose
  # Make SVN checkout, initialize hg repository with first SVN revision
$ hgimportsvn http://python-nose.googlecode.com/svn/trunk
hgimportsvn svn://changwei.dyn.webahead.ibm.com
$ cd trunk
  # Pull all history from SVN, creating a new hg changeset for each SVN rev
$ hgpullsvn

#+END_SRC


** 2个命令创建一个Mercuria仓库，
> hg init
> hg serve，
通过这两个命令你就可以拥有一个通过HTTP协议访问的mercurial仓库， 你可以方便的通过客户端通过命令访问，或者你可以轻松的使用浏览器来浏览当前的代码。

** 方便的分布式功能
上一次在印度我想在一台新电脑上安装源代码，无奈网络速度太慢，于是乎，我找到一个存有源码的机器，hg serve，这样我得到了一个本地服务器，通过它，我在1分钟内拿到了代码，然后将hgrc(一个mercurial的配置文件)的URL指向在中国的服务器，继续更新后面的几个patch。 将一个1个小时的操作变成2分钟的操作。

如果你急需要某个patch, 但是你的同事还没来得及提交到服务器上去，没关系，你大可以将自己的workingcopy指向同事的电脑， 运行hg pull就可以从他那里及时的拿到最新的代码。

没有branch的痛苦, 没有branch是因为每个人都是一个branch -_-!!!

** 便捷的本地提交
使用Mercurial，你可以在没有网络的情况下通过
> hg ci
进行本地提交，再也无需因为没有网络时候患上“写代码没有SCM恐惧症”，你也可以通过这个命令在日常开发中即达到小步前进，又不用每10分钟非得跑一遍测试。

** 离线操作
不论是Mercurial的提交或者是diff，rollback，strip, merge都可以在没有网络的情况下进行，想像一下在中国开发，服务器在美国的痛苦：那缓慢爬行的小乌龟。

** 速度优势
Mercurial是增量存储，并且它会每隔一段时间进行对整个Repository打一个快照，这样当你去clone repository(相当于svn checkout)的时候，它可以找到最近的一个快照，并在它的基础上应用后续的patch。

** 基于patch的管理
Mercurial将你的提交作为一个patch管理， 你可以很容易拿到别人的patch，通过hg客户端或者linux上的 patch命令将别人最新的修正打在你的工作目录里面。

** 更多的便捷操作
你想将本地的某些提交取消? hg strip
你想将server上的某些changeset取消？hg backout
你想订制hg log的输出方式？定义自己的hg template。


这个工具在国内很少人使用，所以中文资料匮乏．只有官方的website上有一些少得可怜的中文资料了．不过总体上来说，hg还是比较好用的。

这里绍一下hg服务器的配置。关于hg在基本用法参见mercrial的官方网站。在做以下操作时，请到 http://www.selenic.com/mercurial/下载安装hg.

1.建立用户hgrepo

其它用户将用这个账户用hg服务器push代码。

useradd hgrepo -d /home/hgrepo # add user hgrepo
passwd hgrepo

2.建立hg代码仓库

如果代码仓库名称为project.hg,则可用如下命令。

cd /home/hgrepo
mkdir project.hg
cd project.hg
hg init # 初始化代码仓库
建立一个测试文件

echo "hello, mercurial" > sample.txt
hg add  # add
hg ci     # check in

3. 打开http

打开一个端口，让远程用户可以clone仓库中的代码.
在打开端口前请确定文件权限正确。

更改文件权限
chown hgrepo.hgrepo /home/hgrepo/project.hg -R
chmod og+rw /home/hgrepo/project.hg -R
打开端口

cd  /home/hgrepo/project.hg -R
hg serve -p 8002 &
可将上面两行加入/etc/rc.local这样就可以在开机的时候自动运行了。

4.使用hg

完成步骤3以后，我们就可以使用了。

clone到本地

例如你的服务器的名字为test.

hg clone http://test:8002
然后在本地目录就会出现一个project.hg的一个copy.

修改Client端的配置

更改.hg/hgrc，加上default-push和username
<#+BEGIN_SRC >
[paths]
default = http://test:8002
default-push = ssh://hgrepo@test//home/hgrepo/project.hg/
[ui]
username=shaohui.zheng

[paths]
default = http://9.123.157.55:8000
default-push = ssh://will@9.123.157.55//home/will/ideas/
[ui]
username=will

#+END_SRC
这样你就可用hg push 向服务器提交code了。这时服务器会问你passward,这个password就是用户hgrepo的password.

Good Luck.

** My setup

hg clone http://changweilaptop.dyn.webahead.ibm.com:8000/ ideas


hg clone http://9.186.119.53:8000/ ideas

** How to use Emacs to work with Mercurial

http://xtalk.msk.su/~ott/en/writings/emacs-vcs/EmacsMercurial.html


*** revert files

hg revert .amsn/ -r 385

首先，使用hg grep找到被删除的文件恢复。此命令的输出将显示该文件的最新版本是目前的，以及对已删除文件的路径。二，运行hg revert -r
<revision number> <path to deleted file>被删除的文件现在在你的工作拷贝，准备送回头部。


*** 4.2. How to declare trust

Users can add settings to their $HOME/.hgrc to tell Mercurial to trust other users. For instance, if Bob has decided he can trust Alice not to try to delete his files when he looks at her repository, he could add:

[trusted]
users = alice, carl, dan

Alternately, Bob can decide to trust a group of people (as specified in an operating system group)

[trusted]
groups = dev-team


** 比较两个 branch

  http://stackoverflow.com/questions/4731190/how-to-show-the-diff-specific-to-a-named-branch-in-mercurial


#+BEGIN_SRC
  109  hg branches
  110  hg branch
  111  hg branch '多维度设置采购计划控制参数'
  112  hg branch
  113  hg bookmark '多维度设置采购计划控制参数'
  114  hg bookmark '多维度设置采购计划控制参数init'
  115  hg branchdiff .
  116  hg st
  117  hg branchdiff .
  118  hg ci -m "测试branch之间的比较"
  119  hg branchdiff .
  120  hg update default
  121  hg branches
  126  hg merge  '多维度设置采购计划控制参数'
#+END_SRC

In your specific example I think you could get a list of of just d and e using:

hg log -r "branch('foo') - branch('default')"
where that - is defined as:

"x - y"
      Changesets in x but not in y.
Getting the diff from a to e could be done as:

hg diff -r "ancestor(default, foo)" -r foo


Another way to do this, useful also for branches that you have already merged to default is:

hg diff -r "max(ancestors(foo) and branch(default)):foo"
Though that can be a pit of a pain, so i'd recommend setting up an alias by adding something like:
#+BEGIN_SRC

[alias]
branchdiff = diff -r "max(ancestors('$1') and branch(default)):'$1'"
To your Mercurial.INI/hgrc which you can then use like this:

hg branchdiff <branch name>
or

hg branchdiff .

#+END_SRC


